-- ============================================================
-- COMBINED SCHEMA — jin-dashboard dev Supabase project bootstrap
-- Generated by concatenating schema.sql + schema_v2.sql ... schema_v39.sql
-- in this exact numeric order. Intended for a ONE-TIME run against an
-- EMPTY/fresh dev Supabase project's SQL Editor.
--
-- NOTE: schema_v6.sql was empty (0 bytes) in the source repo — included
-- as a marker only, no statements from it.
--
-- Statements are wrapped in a single transaction (BEGIN/COMMIT) so a
-- failure partway through rolls back cleanly instead of leaving a
-- half-applied schema. If your SQL Editor session errors on multi-
-- statement transactions, you can remove the BEGIN/COMMIT lines and
-- run the rest as-is (each file's statements were written to be safe
-- to (re)run individually — CREATE ... IF NOT EXISTS / ON CONFLICT DO
-- NOTHING patterns are used throughout).
-- ============================================================

BEGIN;


-- ================================================================
-- SOURCE FILE: schema.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. 팀원 테이블
create table if not exists members (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  part text not null check (part in ('코어', '비즈')),
  created_at timestamp with time zone default now()
);

-- 2. 업무 테이블
create table if not exists tasks (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  part text not null check (part in ('코어', '비즈')),
  type text not null check (type in ('기획', '개선', '운영')),
  assignee_id uuid references members(id) on delete set null,
  status text not null default '진행필요' check (status in ('진행필요', '진행중', '완료')),
  start_date date,
  mid_date date,
  end_date date,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. 맥락/노트 테이블
create table if not exists notes (
  id uuid default gen_random_uuid() primary key,
  task_id uuid references tasks(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default now()
);

-- 4. 첨부파일 테이블
create table if not exists attachments (
  id uuid default gen_random_uuid() primary key,
  task_id uuid references tasks(id) on delete cascade not null,
  name text not null,
  type text not null check (type in ('파일', '링크')),
  url text not null,
  created_at timestamp with time zone default now()
);

-- 5. RLS 비활성화 (단일 사용자 앱 — 앱 레벨 auth로 보호)
alter table members disable row level security;
alter table tasks disable row level security;
alter table notes disable row level security;
alter table attachments disable row level security;

-- 6. updated_at 자동 갱신 트리거
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger tasks_updated_at
  before update on tasks
  for each row execute function update_updated_at();

-- 7. 팀원 초기 데이터
insert into members (name, part) values
  ('김다슬', '코어'),
  ('최도담', '코어'),
  ('강은정', '코어'),
  ('기윤미', '비즈'),
  ('채미소', '비즈'),
  ('장연희', '비즈'),
  ('이재아', '비즈'),
  ('정희영', '비즈'),
  ('최보명', '비즈'),
  ('여도현', '비즈'),
  ('문혜윤', '비즈')
on conflict do nothing;



-- ================================================================
-- SOURCE FILE: schema_v2.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v2
-- 추가 테이블: quick_memos, meetings, learning_resources
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. 빠른 메모 테이블
create table if not exists quick_memos (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null default '',
  tag text not null default '업무관련' check (tag in ('업무관련', '회의관련', '아이디어')),
  created_at timestamp with time zone default now()
);

-- 2. 회의록 테이블
--    notes: jsonb 배열 [{title, content, created_at}]
create table if not exists meetings (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  meeting_date date,
  notes jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. 학습자료 테이블
--    notes: jsonb 배열 [{title, content, created_at}]
create table if not exists learning_resources (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  source text not null default '',
  notes jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 4. RLS 활성화 + 인증된 사용자만 접근 허용
alter table quick_memos enable row level security;
alter table meetings enable row level security;
alter table learning_resources enable row level security;

create policy "auth_all" on quick_memos for all to authenticated using (true) with check (true);
create policy "auth_all" on meetings for all to authenticated using (true) with check (true);
create policy "auth_all" on learning_resources for all to authenticated using (true) with check (true);

-- 5. updated_at 자동 갱신 트리거
--    update_updated_at() 함수는 schema.sql에 이미 정의됨
--    없을 경우를 대비해 create or replace로 재정의
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger meetings_updated_at
  before update on meetings
  for each row execute function update_updated_at();

create trigger learning_resources_updated_at
  before update on learning_resources
  for each row execute function update_updated_at();


-- ================================================================
-- SOURCE FILE: schema_v3.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v3
-- 업무-회의록 양방향 연동 (junction table)
-- Supabase SQL 에디터에서 실행
-- ============================================

-- 업무 ↔ 회의록 연동 테이블
create table if not exists task_meeting_links (
  id uuid default gen_random_uuid() primary key,
  task_id uuid not null references tasks(id) on delete cascade,
  meeting_id uuid not null references meetings(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(task_id, meeting_id)
);

-- RLS 활성화 + 인증된 사용자만 접근
alter table task_meeting_links enable row level security;
create policy "auth_all" on task_meeting_links for all to authenticated using (true) with check (true);


-- ================================================================
-- SOURCE FILE: schema_v4.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v4
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. tasks: 작업월 배열 + 성과분류 컬럼 추가
alter table tasks add column if not exists work_months text[] not null default '{}';
alter table tasks add column if not exists achievement_category text
  check (achievement_category in ('성과', '개선', '리소스', '수명', '기타'));

-- 2. members: 팀장 파트 허용
alter table members drop constraint if exists members_part_check;
alter table members add constraint members_part_check
  check (part in ('코어', '비즈', '팀장'));

-- 3. quick_memos: 공지 태그 추가
alter table quick_memos drop constraint if exists quick_memos_tag_check;
alter table quick_memos add constraint quick_memos_tag_check
  check (tag in ('업무관련', '회의관련', '아이디어', '공지'));

-- 4. 기존 v1 테이블 RLS 활성화 (보안)
alter table tasks enable row level security;
alter table notes enable row level security;
alter table attachments enable row level security;
alter table members enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'tasks' and policyname = 'auth_all') then
    create policy "auth_all" on tasks for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'notes' and policyname = 'auth_all') then
    create policy "auth_all" on notes for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'attachments' and policyname = 'auth_all') then
    create policy "auth_all" on attachments for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'members' and policyname = 'auth_all') then
    create policy "auth_all" on members for all to authenticated using (true) with check (true);
  end if;
end $$;

-- 5. 1on1 세션 테이블
create table if not exists one_on_ones (
  id uuid default gen_random_uuid() primary key,
  member_id uuid not null references members(id) on delete cascade,
  session_date date,
  notes jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
alter table one_on_ones enable row level security;
create policy "auth_all" on one_on_ones for all to authenticated using (true) with check (true);
create trigger one_on_ones_updated_at before update on one_on_ones
  for each row execute function update_updated_at();

-- 6. 1on1 템플릿 테이블 (row 1개만 사용)
create table if not exists one_on_one_template (
  id uuid default gen_random_uuid() primary key,
  content text not null default '',
  updated_at timestamp with time zone default now()
);
alter table one_on_one_template enable row level security;
create policy "auth_all" on one_on_one_template for all to authenticated using (true) with check (true);
create trigger one_on_one_template_updated_at before update on one_on_one_template
  for each row execute function update_updated_at();

do $$
begin
  if not exists (select 1 from one_on_one_template) then
    insert into one_on_one_template (content) values (
      E'## 최근 업무 현황\n\n\n## 어려운 점 / 개선 요청\n\n\n## 성장 / 역량 개발\n\n\n## 기타 이야기'
    );
  end if;
end $$;


-- ================================================================
-- SOURCE FILE: schema_v5.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v5
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. notes: 수정 일시 컬럼 추가
alter table notes add column if not exists edited_at timestamp with time zone;


-- ================================================================
-- SOURCE FILE: schema_v6.sql
-- ================================================================
-- (empty file — no statements)


-- ================================================================
-- SOURCE FILE: schema_v7.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v7
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1on1 sessions: 제목 컬럼 추가
alter table one_on_ones add column if not exists title text;

-- 학습자료: 태그 배열 + 매체 구분 추가
alter table learning_resources add column if not exists tags text[] default '{}';
alter table learning_resources add column if not exists media_type text;


-- ================================================================
-- SOURCE FILE: schema_v8.sql
-- ================================================================
-- ============================================
-- 인사기획팀 생산성 앱 DB 스키마 v8
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- tasks.part 에 '개인' 값 허용
alter table tasks drop constraint if exists tasks_part_check;
alter table tasks add constraint tasks_part_check
  check (part in ('코어', '비즈', '팀장', '개인'));


-- ================================================================
-- SOURCE FILE: schema_v9.sql
-- ================================================================
-- schema_v9.sql
-- 1. my_feedback table (팀장 개인 피드백 수집)
CREATE TABLE IF NOT EXISTS my_feedback (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  month text NOT NULL,          -- 'YYYY-MM'
  content text NOT NULL DEFAULT '',
  feedback_type text NOT NULL DEFAULT '일반',  -- '긍정' | '부정' | '요구사항' | '일반'
  created_at timestamptz DEFAULT now()
);
ALTER TABLE my_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "my_feedback_auth" ON my_feedback
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 2. tasks.retrospective column (업무완료 회고)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS retrospective jsonb;


-- ================================================================
-- SOURCE FILE: schema_v10.sql
-- ================================================================
-- schema_v10.sql
-- 1. my_feedback: 날짜 선택 + 피드백 제공자 추가
ALTER TABLE my_feedback ADD COLUMN IF NOT EXISTS feedback_date date;
ALTER TABLE my_feedback ADD COLUMN IF NOT EXISTS from_member text;

-- 2. one_on_ones: 다음 약속 컬럼 추가
ALTER TABLE one_on_ones ADD COLUMN IF NOT EXISTS next_appointment text;


-- ================================================================
-- SOURCE FILE: schema_v11.sql
-- ================================================================
-- schema_v11.sql
-- notes 테이블에 사용자 정의 제목 컬럼 추가
ALTER TABLE notes ADD COLUMN IF NOT EXISTS title text;


-- ================================================================
-- SOURCE FILE: schema_v12.sql
-- ================================================================
-- schema_v12.sql
-- PC-모바일 연동: localStorage 데이터를 Supabase에 저장
CREATE TABLE IF NOT EXISTS user_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz DEFAULT now()
);

-- 기본 행 미리 삽입 (없으면 upsert로 처리하므로 필수 아님)


-- ================================================================
-- SOURCE FILE: schema_v13.sql
-- ================================================================
-- v13: 첨부파일 meeting_id 추가 + task_id nullable 처리
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS meeting_id uuid REFERENCES meetings(id) ON DELETE CASCADE;
ALTER TABLE attachments ALTER COLUMN task_id DROP NOT NULL;

-- Supabase Storage 버킷 생성 (대시보드에서 직접 수행):
-- Storage > New bucket > 이름: "attachments" > Public 체크 > Create
-- 또는 아래 SQL 실행 (storage 스키마 접근 가능한 경우):
-- INSERT INTO storage.buckets (id, name, public) VALUES ('attachments', 'attachments', true) ON CONFLICT DO NOTHING;


-- ================================================================
-- SOURCE FILE: schema_v14.sql
-- ================================================================
-- v14: schedule_tag 추가 (일정 플래닝 레이어)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS schedule_tag TEXT CHECK (schedule_tag IN ('today', 'tomorrow', 'this_week'));


-- ================================================================
-- SOURCE FILE: schema_v15.sql
-- ================================================================
-- v15: task_todos 테이블 생성 (업무 내 할일 단위, 일정 플래닝 레이어)
-- v14의 tasks.schedule_tag는 사용하지 않으므로 실행하지 않아도 됩니다.
CREATE TABLE IF NOT EXISTS task_todos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id uuid REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  schedule_tag TEXT CHECK (schedule_tag IN ('today', 'tomorrow', 'this_week')),
  done BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- RLS (tasks와 동일 패턴)
ALTER TABLE task_todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_task_todos" ON task_todos FOR ALL USING (true) WITH CHECK (true);


-- ================================================================
-- SOURCE FILE: schema_v16.sql
-- ================================================================
-- v16: 태스크 단축명 + 할일 목표날짜 (날짜기반 일정 플래닝)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE task_todos ADD COLUMN IF NOT EXISTS target_date DATE;

-- 기존 schedule_tag → target_date 마이그레이션
UPDATE task_todos SET target_date = CURRENT_DATE WHERE schedule_tag = 'today' AND target_date IS NULL AND done = false;
UPDATE task_todos SET target_date = CURRENT_DATE + INTERVAL '1 day' WHERE schedule_tag = 'tomorrow' AND target_date IS NULL AND done = false;
UPDATE task_todos SET target_date = (date_trunc('week', CURRENT_DATE) + INTERVAL '4 days')::DATE WHERE schedule_tag = 'this_week' AND target_date IS NULL AND done = false;


-- ================================================================
-- SOURCE FILE: schema_v17.sql
-- ================================================================
-- v17: task_todos 완료 시각 추가 (홈탭 금주 완료 아카이빙)
ALTER TABLE task_todos ADD COLUMN IF NOT EXISTS done_at TIMESTAMPTZ;


-- ================================================================
-- SOURCE FILE: schema_v18.sql
-- ================================================================
-- v18: soft-delete (archive) support for members
ALTER TABLE members ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;


-- ================================================================
-- SOURCE FILE: schema_v19.sql
-- ================================================================
-- v19: 안건 매트릭스 (agenda matrix)
-- meetings.category 기반으로 파트별 안건 흐름 추적
-- 3-tier: meeting_category(코어/비즈) → agenda_group(범주) → agenda_item(안건 행)
-- agenda_updates: 안건 × 회의 = 셀 노트 (희소 매트릭스)

-- ── 1. 범주 (평가/보상, 노무 등) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS agenda_groups (
  id         uuid    DEFAULT gen_random_uuid() PRIMARY KEY,
  -- meetings.category 와 동일한 값 사용 (코어, 비즈 등)
  category   text    NOT NULL,
  name       text    NOT NULL,
  color      text    NOT NULL DEFAULT '#9CA3AF',
  sort_order integer NOT NULL DEFAULT 0,
  is_open    boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  UNIQUE (category, name)
);

-- ── 2. 안건 행 ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS agenda_items (
  id              uuid    DEFAULT gen_random_uuid() PRIMARY KEY,
  group_id        uuid    NOT NULL REFERENCES agenda_groups(id) ON DELETE CASCADE,
  title           text    NOT NULL,
  item_type       text    NOT NULL DEFAULT 'do'
                          CHECK (item_type IN ('do', 'fb', 'rp', 'ag')),
  status          text    NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'hold', 'done')),
  linked_task_id  uuid    REFERENCES tasks(id) ON DELETE SET NULL,
  sort_order      integer NOT NULL DEFAULT 0,
  hidden          boolean NOT NULL DEFAULT false,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- ── 3. 셀 노트 (안건 × 회의) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS agenda_updates (
  id             uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  agenda_item_id uuid NOT NULL REFERENCES agenda_items(id) ON DELETE CASCADE,
  meeting_id     uuid NOT NULL REFERENCES meetings(id)     ON DELETE CASCADE,
  note           text NOT NULL DEFAULT '',
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now(),
  UNIQUE (agenda_item_id, meeting_id)
);

-- ── 4. RLS (다른 테이블과 동일 패턴) ────────────────────────────
ALTER TABLE agenda_groups  ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_items   ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_all" ON agenda_groups  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all" ON agenda_items   FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all" ON agenda_updates FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── 5. updated_at 트리거 ─────────────────────────────────────────
CREATE TRIGGER agenda_items_updated_at
  BEFORE UPDATE ON agenda_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER agenda_updates_updated_at
  BEFORE UPDATE ON agenda_updates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── 6. 인덱스 ────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_agenda_groups_category  ON agenda_groups  (category, sort_order);
CREATE INDEX IF NOT EXISTS idx_agenda_items_group      ON agenda_items   (group_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_agenda_updates_item     ON agenda_updates (agenda_item_id);
CREATE INDEX IF NOT EXISTS idx_agenda_updates_meeting  ON agenda_updates (meeting_id);

-- ── 7. meetings 테이블에 category 컬럼이 없으면 추가 ─────────────
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS category text;


-- ================================================================
-- SOURCE FILE: schema_v20.sql
-- ================================================================
-- v20: period_journals — 주간/월간 회고 저장
-- period_key 형식: 'week_2026-07-28' (월요일 기준) | 'month_2026-07'

CREATE TABLE IF NOT EXISTS period_journals (
  id          uuid    DEFAULT gen_random_uuid() PRIMARY KEY,
  period_key  text    NOT NULL UNIQUE,
  period_type text    NOT NULL CHECK (period_type IN ('weekly', 'monthly')),
  content     text    NOT NULL DEFAULT '',
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

ALTER TABLE period_journals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON period_journals FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER period_journals_updated_at
  BEFORE UPDATE ON period_journals
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX IF NOT EXISTS idx_period_journals_key ON period_journals (period_key);


-- ================================================================
-- SOURCE FILE: schema_v21.sql
-- ================================================================
-- v21: period_journals에 3필드 추가 (주간/월간 회고 구조화)
ALTER TABLE period_journals ADD COLUMN IF NOT EXISTS good       text NOT NULL DEFAULT '';
ALTER TABLE period_journals ADD COLUMN IF NOT EXISTS bad        text NOT NULL DEFAULT '';
ALTER TABLE period_journals ADD COLUMN IF NOT EXISTS next_focus text NOT NULL DEFAULT '';


-- ================================================================
-- SOURCE FILE: schema_v22.sql
-- ================================================================
-- v22: user_preferences — 설정 DB 동기화 (메뉴 순서/가시성, 조직 구조)
-- localStorage 의존 제거 → Mac/Windows 간 설정 공유 가능

CREATE TABLE IF NOT EXISTS user_preferences (
  key        text PRIMARY KEY,
  value      jsonb NOT NULL DEFAULT 'null'::jsonb,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON user_preferences
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- members 테이블에 role 컬럼 추가 (직책: 팀원/파트장/팀장)
ALTER TABLE members ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT '팀원';


-- ================================================================
-- SOURCE FILE: schema_v23.sql
-- ================================================================
-- v23: annual goals (yeongan-mokpyo)
-- category (5 fixed values, pill filter) -> annual_goal_items (mid-tier "agenda") -> annual_goal_tasks (leaf "subtask")
-- fully independent of agenda_* tables

-- 1. annual_goal_items
CREATE TABLE IF NOT EXISTS annual_goal_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('1. 인재 확보', '2. 검증과 정렬', '3. 유지와 보상', '4. 지속가능성', '5. 확장 기반')),
  title text NOT NULL,
  color text NOT NULL DEFAULT '#3B82F6',
  sort_order integer NOT NULL DEFAULT 0,
  is_open boolean NOT NULL DEFAULT true,
  roadmap_start_date date,
  roadmap_end_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (category, title)
);

-- 2. annual_goal_tasks
CREATE TABLE IF NOT EXISTS annual_goal_tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES annual_goal_items(id) ON DELETE CASCADE,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hold', 'done')),
  description text,
  maturity_level integer CHECK (maturity_level BETWEEN 1 AND 3),
  maturity_rationale text,
  track text CHECK (track IN ('A', 'B', 'C')),
  hr_importance text CHECK (hr_importance IN ('상', '중', '하')),
  hr_urgency text CHECK (hr_urgency IN ('상', '중', '하')),
  suggested_period text,
  hrm_function text,
  notes text,
  exec_importance text CHECK (exec_importance IN ('상', '중', '하')),
  agreed_priority text CHECK (agreed_priority IN ('1순위', '2순위', '유예')),
  roadmap_start_date date,
  roadmap_end_date date,
  roadmap_rank integer,
  assignee_id uuid REFERENCES members(id) ON DELETE SET NULL,
  mid_date date,
  due_date date,
  target_date date,
  sort_order integer NOT NULL DEFAULT 0,
  hidden boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 3. annual_goal_task_notes (mirrors sub_task_notes)
CREATE TABLE IF NOT EXISTS annual_goal_task_notes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id uuid NOT NULL REFERENCES annual_goal_tasks(id) ON DELETE CASCADE,
  title text,
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now(),
  edited_at timestamptz
);

-- 4. reuse attachments table
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS annual_goal_item_id uuid REFERENCES annual_goal_items(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS annual_goal_task_id uuid REFERENCES annual_goal_tasks(id) ON DELETE CASCADE;

-- 5. RLS
ALTER TABLE annual_goal_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE annual_goal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE annual_goal_task_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_all" ON annual_goal_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all" ON annual_goal_tasks FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all" ON annual_goal_task_notes FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. updated_at triggers (reuses update_updated_at() from base schema.sql)
CREATE TRIGGER annual_goal_items_updated_at BEFORE UPDATE ON annual_goal_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER annual_goal_tasks_updated_at BEFORE UPDATE ON annual_goal_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 7. indexes
CREATE INDEX IF NOT EXISTS idx_annual_goal_items_category ON annual_goal_items (category, sort_order);
CREATE INDEX IF NOT EXISTS idx_annual_goal_tasks_item ON annual_goal_tasks (item_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_annual_goal_tasks_assignee ON annual_goal_tasks (assignee_id);
CREATE INDEX IF NOT EXISTS idx_annual_goal_task_notes_task ON annual_goal_task_notes (task_id);
CREATE INDEX IF NOT EXISTS idx_attachments_annual_goal_item ON attachments (annual_goal_item_id);
CREATE INDEX IF NOT EXISTS idx_attachments_annual_goal_task ON attachments (annual_goal_task_id);


-- ================================================================
-- SOURCE FILE: schema_v24.sql
-- ================================================================
-- v24: annual_goal_items에 목표 데드라인 컬럼 추가 (진척률 D-day 표시용)

ALTER TABLE annual_goal_items ADD COLUMN IF NOT EXISTS target_deadline date;


-- ================================================================
-- SOURCE FILE: schema_v25.sql
-- ================================================================
-- v25: annual_goal_category_labels
-- 카테고리 표시 이름을 편집 가능하게 만들기 위한 작은 매핑 테이블.
-- category_key는 annual_goal_items.category에 저장된 고정 키('1. 인재 확보' 등)를 그대로 사용하고,
-- name만 편집 가능한 표시용 이름으로 분리한다. 기존 안건/세부task 데이터의 category 값은 손대지 않는다.

CREATE TABLE IF NOT EXISTS annual_goal_category_labels (
  category_key text PRIMARY KEY,
  name text NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE annual_goal_category_labels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_all" ON annual_goal_category_labels FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER annual_goal_category_labels_updated_at BEFORE UPDATE ON annual_goal_category_labels FOR EACH ROW EXECUTE FUNCTION update_updated_at();

INSERT INTO annual_goal_category_labels (category_key, name) VALUES
  ('1. 인재 확보', '인재 확보'),
  ('2. 검증과 정렬', '검증과 정렬'),
  ('3. 유지와 보상', '유지와 보상'),
  ('4. 지속가능성', '지속가능성'),
  ('5. 확장 기반', '확장 기반')
ON CONFLICT (category_key) DO NOTHING;


-- ================================================================
-- SOURCE FILE: schema_v26.sql
-- ================================================================
-- v26: manual_achievements — 완료성과 탭에서 자동 집계 외에 수기로 추가하는 성과 항목

CREATE TABLE IF NOT EXISTS manual_achievements (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL DEFAULT '성과' CHECK (category IN ('성과', '개선', '리소스', '수명', '기타')),
  content text NOT NULL DEFAULT '',
  month text NOT NULL, -- 'YYYY-MM'
  created_at timestamptz DEFAULT now()
);

ALTER TABLE manual_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_all" ON manual_achievements FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ================================================================
-- SOURCE FILE: schema_v27.sql
-- ================================================================
-- v27: 완료 성과 탭 전면 재설계
-- - agenda_sub_tasks(프로젝트 탭 세부task)에 기획/운영/개선 태그 컬럼 추가
-- - manual_achievements를 그룹(agenda_groups) + 기획/운영/개선 태그 기반으로 재생성
--   (v26의 성과/개선/리소스/수명/기타 카테고리 체계는 폐기)

-- SKIPPED (dev environment, 2026-08-14): `agenda_sub_tasks` has no CREATE TABLE
-- anywhere in schema.sql..schema_v39.sql (one of the 13 undocumented tables from
-- docs/autosave-audit.md §6b/§7 — it exists in the real prod DB via a path not
-- captured in these files). Running this ALTER against a fresh dev project errors
-- with "relation agenda_sub_tasks does not exist". Commented out so the rest of
-- the combined script can run to completion. See docs/autosave-db-design.md
-- "Dev Environment Known Gaps" section for the full list of screens/tables this
-- dev project intentionally cannot test.
-- ALTER TABLE agenda_sub_tasks
--   ADD COLUMN IF NOT EXISTS achievement_type text
--   CHECK (achievement_type IN ('기획', '운영', '개선'));

DROP TABLE IF EXISTS manual_achievements;

CREATE TABLE manual_achievements (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_id uuid NOT NULL REFERENCES agenda_groups(id) ON DELETE CASCADE,
  title text NOT NULL,
  achievement_type text CHECK (achievement_type IN ('기획', '운영', '개선')),
  month text NOT NULL, -- 완료 처리 월, 'YYYY-MM'
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE manual_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_all" ON manual_achievements FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ================================================================
-- SOURCE FILE: schema_v28.sql
-- ================================================================
-- v28: 공통업무 팀 로그 (team-log) — 팀원 4명 공용, 비로그인 접근용 독립 테이블
-- 기존 테이블과 완전히 분리. RLS로 anon은 이 테이블만 select/insert 가능,
-- 다른 모든 테이블은 여전히 authenticated 전용이라 접근 불가.

CREATE TABLE team_log_entries (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  author text NOT NULL,
  entry_type text NOT NULL CHECK (entry_type IN ('업무기록', '보고일정')),
  entry_date date NOT NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE team_log_entries ENABLE ROW LEVEL SECURITY;

-- anon(비로그인) 접근 허용 — 이 테이블에만 한정. 다른 테이블은 영향 없음.
CREATE POLICY "team_log_anon_select" ON team_log_entries FOR SELECT TO anon USING (true);
CREATE POLICY "team_log_anon_insert" ON team_log_entries FOR INSERT TO anon WITH CHECK (true);

-- 기존 로그인 계정도 동일하게 조회/작성 가능
CREATE POLICY "team_log_auth_all" ON team_log_entries FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX team_log_entries_date_idx ON team_log_entries (entry_date DESC);


-- ================================================================
-- SOURCE FILE: schema_v29.sql
-- ================================================================
-- v29: team_log_entries를 마스터키(service role) 전용으로 전환
-- API가 이제 service role 키로 직접 접근하므로(RLS 우회), anon에게 열어줬던
-- select/insert 정책을 제거한다. 이제 브라우저의 anon key로는 이 테이블도 직접 못 건드린다.

DROP POLICY IF EXISTS "team_log_anon_select" ON team_log_entries;
DROP POLICY IF EXISTS "team_log_anon_insert" ON team_log_entries;


-- ================================================================
-- SOURCE FILE: schema_v30.sql
-- ================================================================
-- v30: /team-log을 '프로젝트' 탭 스타일(그룹 → 항목 → 서브태스크)로 재구성.
-- 회의록 매트릭스(agenda_updates류)와 로드맵 뷰는 이 팀 로그에는 두지 않음 — 3단 구조만.
-- v28의 flat entries 구조는 이걸로 대체되어 더 이상 쓰지 않으므로 제거.

DROP TABLE IF EXISTS team_log_entries;

CREATE TABLE team_log_groups (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#4C7FE0',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE team_log_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_id uuid NOT NULL REFERENCES team_log_groups(id) ON DELETE CASCADE,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hold', 'done')),
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE team_log_subtasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES team_log_items(id) ON DELETE CASCADE,
  author text NOT NULL,
  entry_type text NOT NULL DEFAULT '업무기록' CHECK (entry_type IN ('업무기록', '보고일정')),
  entry_date date NOT NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE team_log_groups   ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_log_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_log_subtasks ENABLE ROW LEVEL SECURITY;

-- anon 정책 없음 — service role(마스터키)로만 접근. 기존 로그인 계정은 authenticated로 계속 접근 가능.
CREATE POLICY "team_log_groups_auth_all"   ON team_log_groups   FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "team_log_items_auth_all"    ON team_log_items    FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "team_log_subtasks_auth_all" ON team_log_subtasks FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX team_log_items_group_idx    ON team_log_items (group_id, sort_order);
CREATE INDEX team_log_subtasks_item_idx  ON team_log_subtasks (item_id, sort_order);
CREATE INDEX team_log_subtasks_date_idx  ON team_log_subtasks (entry_date DESC);


-- ================================================================
-- SOURCE FILE: schema_v31.sql
-- ================================================================
-- v31: /team-log에 '일상'(자유 메모 보드)과 '회의록' 섹션 추가
-- 기존 업무(그룹→항목→서브태스크) 구조는 그대로 유지, 이 두 테이블만 새로 추가.

CREATE TABLE team_log_notes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  author text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE team_log_meetings (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  meeting_date date NOT NULL,
  attendees text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE team_log_notes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_log_meetings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "team_log_notes_auth_all"    ON team_log_notes    FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "team_log_meetings_auth_all" ON team_log_meetings FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX team_log_meetings_date_idx ON team_log_meetings (meeting_date DESC);


-- ================================================================
-- SOURCE FILE: schema_v32.sql
-- ================================================================
-- v32: /team-log에 '일정' 섹션 추가. 업무 항목/서브태스크/회의록에서 연동(추가) 가능.

CREATE TABLE team_log_schedule (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  event_date date NOT NULL,
  note text NOT NULL DEFAULT '',
  source_type text CHECK (source_type IN ('item', 'subtask', 'meeting')),
  source_id uuid,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE team_log_schedule ENABLE ROW LEVEL SECURITY;

CREATE POLICY "team_log_schedule_auth_all" ON team_log_schedule FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX team_log_schedule_date_idx ON team_log_schedule (event_date);


-- ================================================================
-- SOURCE FILE: schema_v33.sql
-- ================================================================
-- v33: team-log 일정을 월별 다이어리 그리드(주차×담당자)로 재구성하기 위한 필드/테이블 추가

ALTER TABLE team_log_schedule ADD COLUMN assignee text NOT NULL DEFAULT '';
ALTER TABLE team_log_schedule ADD COLUMN tag text;

CREATE TABLE team_log_members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE team_log_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "team_log_members_auth_all" ON team_log_members FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ================================================================
-- SOURCE FILE: schema_v34.sql
-- ================================================================
-- ============================================
-- v34: 팀명 자유화 (조직 개편 대응)
-- 배경: '코어'→'인사관리팀', '비즈'→'인재전략팀'으로 팀명 변경.
--       members.part / tasks.part 에 특정 팀명만 허용하는 CHECK 제약이 있어
--       앞으로 팀명이 또 바뀌어도 코드/DB 수정 없이 반영되도록 제약을 제거하고,
--       기존 데이터를 새 팀명으로 일괄 변경한다.
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. members.part / tasks.part / meetings.category: 특정 값만 허용하던 CHECK 제약 제거
--    (팀 목록은 이제 설정(user_preferences.org)에서 자유롭게 관리)
alter table members drop constraint if exists members_part_check;
alter table tasks drop constraint if exists tasks_part_check;
alter table meetings drop constraint if exists meetings_category_check;
alter table agenda_groups drop constraint if exists agenda_groups_category_check;

-- 2. 기존 데이터 일괄 rename: 코어 → 인사관리팀, 비즈 → 인재전략팀
update members set part = '인사관리팀' where part = '코어';
update members set part = '인재전략팀' where part = '비즈';

update tasks set part = '인사관리팀' where part = '코어';
update tasks set part = '인재전략팀' where part = '비즈';

update meetings set category = '인사관리팀' where category = '코어';
update meetings set category = '인재전략팀' where category = '비즈';

update agenda_groups set category = '인사관리팀' where category = '코어';
update agenda_groups set category = '인재전략팀' where category = '비즈';


-- ================================================================
-- SOURCE FILE: schema_v35.sql
-- ================================================================
-- ============================================
-- v35: 생각스케치 (무한 캔버스 보드)
-- 추가 테이블: sketch_boards, sketch_cards
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. 보드 테이블 (주제별로 여러 개 생성)
create table if not exists sketch_boards (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 2. 카드 테이블 (보드에 속한 자유배치 텍스트 카드)
--    color: CATEGORY_PALETTE(src/lib/categoryColors.ts) 키와 동일하게 맞춤
create table if not exists sketch_cards (
  id uuid default gen_random_uuid() primary key,
  board_id uuid not null references sketch_boards(id) on delete cascade,
  content text not null default '',
  color text not null default 'blue'
    check (color in ('blue', 'purple', 'teal', 'amber', 'pink', 'green', 'cyan', 'lilac', 'neutral')),
  position_x double precision not null default 0,
  position_y double precision not null default 0,
  width double precision not null default 220,
  height double precision not null default 140,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists sketch_cards_board_id_idx on sketch_cards(board_id);

-- 3. RLS 활성화 + 인증된 사용자만 접근 허용
alter table sketch_boards enable row level security;
alter table sketch_cards enable row level security;

create policy "auth_all" on sketch_boards for all to authenticated using (true) with check (true);
create policy "auth_all" on sketch_cards for all to authenticated using (true) with check (true);

-- 4. updated_at 자동 갱신 트리거
--    update_updated_at() 함수는 schema.sql / schema_v2.sql에 이미 정의됨
create trigger sketch_boards_updated_at
  before update on sketch_boards
  for each row execute function update_updated_at();

create trigger sketch_cards_updated_at
  before update on sketch_cards
  for each row execute function update_updated_at();


-- ================================================================
-- SOURCE FILE: schema_v36.sql
-- ================================================================
-- ============================================
-- v36: 생각스케치 카드 연결/종속 관계
-- 추가 테이블: sketch_edges
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

create table if not exists sketch_edges (
  id uuid default gen_random_uuid() primary key,
  board_id uuid not null references sketch_boards(id) on delete cascade,
  source_card_id uuid not null references sketch_cards(id) on delete cascade,
  target_card_id uuid not null references sketch_cards(id) on delete cascade,
  created_at timestamp with time zone default now()
);

create index if not exists sketch_edges_board_id_idx on sketch_edges(board_id);

alter table sketch_edges enable row level security;
create policy "auth_all" on sketch_edges for all to authenticated using (true) with check (true);


-- ================================================================
-- SOURCE FILE: schema_v37.sql
-- ================================================================
-- ============================================
-- v37: 생각스케치 프레임(그룹) 기능
-- Supabase SQL 에디터에서 전체 실행
-- ============================================

-- 1. sketch_frames 테이블
create table if not exists sketch_frames (
  id          uuid primary key default gen_random_uuid(),
  board_id    uuid not null references sketch_boards(id) on delete cascade,
  title       text not null default '제목 없는 프레임',
  position_x  double precision not null default 0,
  position_y  double precision not null default 0,
  width       double precision not null default 400,
  height      double precision not null default 300,
  collapsed   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists sketch_frames_board_id_idx on sketch_frames(board_id);

-- updated_at 자동 갱신 트리거
create or replace function update_sketch_frames_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger trg_sketch_frames_updated_at
  before update on sketch_frames
  for each row execute function update_sketch_frames_updated_at();

alter table sketch_frames enable row level security;
create policy "auth_all" on sketch_frames for all to authenticated using (true) with check (true);

-- 2. sketch_cards 에 frame_id 컬럼 추가
--    position_x/y 는 frame_id가 null이면 절대좌표, non-null이면 프레임 상대좌표
alter table sketch_cards add column if not exists
  frame_id uuid references sketch_frames(id) on delete set null;

create index if not exists sketch_cards_frame_id_idx on sketch_cards(frame_id);


-- ================================================================
-- SOURCE FILE: schema_v38.sql
-- ================================================================
-- ============================================
-- v38: 홈 타임라인 업무 일정 (schedule_items)
-- 특정 Task/안건에 종속되지 않는, 홈 "오늘의 타임라인" 업무 레인 전용
-- 가벼운 일정 블록. Supabase SQL 에디터에서 전체 실행
-- ============================================

create table if not exists schedule_items (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  item_date       date not null,
  start_hour      double precision not null default 9,
  duration_hours  double precision not null default 1,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists schedule_items_item_date_idx on schedule_items(item_date);

-- updated_at 자동 갱신 트리거 — update_updated_at() 함수는 schema.sql/schema_v2.sql에 이미 정의됨
create trigger trg_schedule_items_updated_at
  before update on schedule_items
  for each row execute function update_updated_at();

alter table schedule_items enable row level security;
create policy "auth_all" on schedule_items for all to authenticated using (true) with check (true);


-- ================================================================
-- SOURCE FILE: schema_v39.sql
-- ================================================================
-- ============================================
-- v39: quick_memos.tag 단일 문자열 → 다중 태그(text[])로 마이그레이션
-- Supabase SQL 에디터에서 전체 실행 (수동 반영 필요 — 이 파일은 앱이 자동으로 적용하지 않음)
--
-- 기존 값은 1개짜리 배열로 감싸서 그대로 보존한다 (`using array[tag]`).
-- 예: '업무관련' → ARRAY['업무관련']
-- ============================================

-- 1. 단일값 전제 체크 제약 제거 (schema_v4.sql에서 추가된 것)
alter table quick_memos drop constraint if exists quick_memos_tag_check;

-- 2. 컬럼 타입 변경: text → text[] (기존 값은 1개짜리 배열로 보존)
alter table quick_memos alter column tag drop default;
alter table quick_memos alter column tag type text[] using array[tag]::text[];
alter table quick_memos alter column tag set default array['업무관련']::text[];
alter table quick_memos alter column tag set not null;

-- 참고: 요소 값 자체에 대한 체크 제약(업무관련/회의관련/아이디어/공지/완료)은
-- 배열 타입에서는 표준 체크로 걸기 까다로워 생략 — 값 검증은 애플리케이션(MemoTag[]) 레벨에서 유지.


COMMIT;
